export 'package:orange_theatre/config/components/internet_exception_widget.dart';
export 'package:orange_theatre/config/components/loading_widget.dart';
export 'package:orange_theatre/views/Movie-Screen/widgets/movies_logo_widget.dart';
export 'package:orange_theatre/views/Movie-Screen/widgets/movies_poster_widget.dart';
export 'package:orange_theatre/views/Movie-Screen/widgets/movies_rating_widget.dart';
export 'package:orange_theatre/views/Movie-Screen/widgets/movies_title_widget.dart';
export 'package:orange_theatre/views/Movie-Screen/widgets/release_revenue_popularity_widget.dart';
export 'package:orange_theatre/views/widgets/top_trending_item.dart';
export 'package:orange_theatre/views/widgets/top_upcoming_item.dart';